### ISSUE TITLE
error in 01_T2_5_select_dispensing.R

### ISSUE THREAD

**Issue by visama** [IMI-ConcePTION/DP1-Neuropathic-pain#8]
In our ccdm-instance person_id is converted to int in R. 

launch_step("p_steps/01_T2_5_select_dispensing.R")
Error in bmerge(xx, ii, seq_along(xx), seq_along(xx), mult = mult, ops = rep(1L,  : 
  Incompatible join types: x.person_id (character) and i.person_id (integer)
Timing stopped at: 1.862 0.024 0.398

@OlgaPaoletti

**Comment by OlgaPaoletti** [comment]
@visama  Thanks for informing me. This is strange because we ran DP1 script in the past but it is true I did some updates.       Are you using the same instance for all ConcePTION (pregnancy algorithm, DPs ...) ?  Did you change your istance recently ((during/after summer)?

**Comment by visama** [comment]
I use new pregnancy algorithm, but rest of the data is as before. I can locate the line of error later today.

**Comment by visama** [comment]
Line 21 causes the error. GABAPENTIN:person_id is char and person_spells_tmp:person_id is int

**Comment by OlgaPaoletti** [comment]
I found the problem. I'm updating the release now

**Comment by OlgaPaoletti** [comment]
Did you tested the updated release, after my comment here? Did it worked?

**Comment by visama** [comment]
I ran the script on 22.9. It should be the new version. I still get the same error as before, so I was not sure if it was updated.

flag_spells_containing_disp_gaba<-unique(better_foverlaps(person_spells_tmp,GABAPENTIN))
 These tables have different type for person_id(char, integer)

**Comment by OlgaPaoletti** [comment]
Ok, now I understand. I updated the release. I hope it works now

**Comment by visama** [comment]
Thank you Olga, it works now. Now the script 03_T2_2_create_components_pregnancy.R produces similar error message:

[1] "Detecting components for algorithm M1"
Error in bmerge(i, x, leftcols, rightcols, roll, rollends, nomatch, mult,  : 
  Incompatible join types: x.person_id (integer) and i.person_id (character)
Timing stopped at: 451.9 24.22 1206

155 line gives an error, when it tries to link selected_dispensing_gaba_pregnancy with D4_study_population_gaba_pregnancy.

sapply(selected_dispensing_gaba_pregnancy, class)
            person_id                  date                codvar       indication_code prescriber_speciality 
          "character"                "Date"           "character"             "integer"           "character" 
> sapply(D4_study_population_gaba_pregnancy, class)
   person_id pregnancy_id 
   "integer"  "character"

Could you fix all the merges in this script?

**Comment by OlgaPaoletti** [comment]
Sure, I'm working on it

**Comment by OlgaPaoletti** [comment]
I just updated the release. Now it should work

**Comment by visama** [comment]
Hmm, it still doesnt work. It gives the same error as before.

**Comment by OlgaPaoletti** [comment]
Sorry it is my fault. I did not explain what to do in detail. The problem was in the step: **launch_step("p_steps/02_T3_2_create_study_population_pregnancy.R")**     so you should rerun from it

**Comment by visama** [comment]
But I downloaded the updated version and ran it from the beginning
